# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "ci" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: PWD
      run: |
        pwd
        
    - name: ll
      run: |
        ls -a
        
    - name: ðŸ”¨ set up xcode version
      run: |
        sudo xcode-select -s /Applications/Xcode_16.1.app
        
    - name: âœ… check xcode version
      run: |
        sudo xcodebuild -version
        
    - name: install swift lint
      run: |
        git clone https://github.com/realm/SwiftLint.git
        cd SwiftLint
        swift build -c release

    - name: Run SwiftLint
      run: |
        ./.build/release/swiftlint lint
        
    - name: Build
      run: |
        xcodebuild -workspace ./MemorialHouse/MemorialHouse.xcworkspace -scheme MemorialHouse
